services:
  backend:
    build:
      context: .
      dockerfile: ./backend/Dockerfile
    container_name: myapp_backend
    ports:
      - "${APP_PORT}:3000"
    environment:
      APP_PORT: ${APP_PORT}
      DB_HOST: ${DB_HOST}
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}
      DB_NAME: ${DB_NAME}
    depends_on:
      - mysql

  redis:
    container_name: myapp_redis
    image: redis

  mysql:
    image: mysql:8
    container_name: myapp_mysql
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_DATABASE: ${DB_NAME}
    ports:
      - "3307:3306"
    volumes:
      - mysql-data:/var/lib/mysql
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: myapp_phpmyadmin
    ports:
      - "8080:80"
    environment:
      PMA_HOST: mysql
volumes:
  mysql-data:
